name: Pull Request
description: Make a pull request
labels: []
body:
  - type: markdown
    attributes:
      value: >
        Thanks for creating a pull request!  Please fill in the template below and review
        the checklist to make sure we can merge this code quickly.

        Note that, when opening your draft PR, you may not have everything filled out - 
        for example, you might develop your test insturctions in parallel to building your
        PR.  That is ok!  But before moving the PR out of draft, please ensure everything
        is prepared. 
  - type: textarea
    id: pull-request-description
    attributes:
      label: Describe the pull request
      description: >
        Provide a clear description of what you propose.  What does it implement?  
        How should it work?
      placeholder: |
        Implemented here is a check to see if, during install, we have the required kubernetes
        permissions to properly deploy the charm.  If we do not, we raise a `BlockedStatus` with
        a clear message.
    validations:
      required: true
  - type: textarea
    id: test-instructions
    attributes:
      label: Instructions for testing
      description: >
        Provide a clear, step by step instruction of how to test this feature.  Provide
        screenshots, scripts, or other instructions as needed.  Even though you have
        unit and integration tests (you have tests, right?), explain here how a human can test
        your code.  
      placeholder: |
        To test normal operation:
        1. `juju deploy myCharm --trust`
        2. (wait for deployment to occur - the charm should progress to `Active`)

        To test the error catch added in this PR:
        1. `juju deploy myCharm` (omitting `--trust`)
        2. (wait for deployment to occur - the charm should progress to 
           `BlockedStatus("Charm missing required permissions - did you deploy with --trust?"))
  - type: textarea
    id: reference-issues
    attributes:
      label: Reference issues
      description: >
        Reference any issues this might be related to (these could also be mentioned in the 
        descriptions above).  If this PR will fully address an open issue, use a 
        [github keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)
        to ensure when this PR closes, the issue is closed. 
      placeholder: |
        This PR closes #XXXX
        #YYYY was considered here
  - type: textarea
    id: checklist
    attributes:
      label: PR checklist
      value: |
        * [] PR includes unit tests on all new code
        * [] something else



  - type: textarea
    id: enhancement-business-case
    attributes:
      label: Why is this enhancement needed?
      description: >
        Describe the problem that this solves, perhaps by citing any existing issues this
        could address.
      placeholder: |
        Currently, whenever this charm is deployed without `--trust`, it goes into `Error`
        and the `debug-log` for the charm does not make it obvious why.  Adding this 
        feature would make it much easier for users to address this misconfiguration. 
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else that might help is solve this problem?
