<!-- Thanks for creating a pull request!  Please fill in the template below and review
the checklist to ensure we can merge this code quickly.

When opening your draft PR, you may not have everything filled out - for example, 
you might develop your test insturctions in parallel to building your
PR.  That is ok!  But before moving the PR out of draft, please ensure everything
is prepared. 

Note that text inside these "<!->" blocks are just tips and will not show up
in the final pull request - no need for you to delete them!
-->
### Pull request description
<!--
Provide a clear description of what you propose.  What does it implement?  
How should it work?

Example:
  Implemented here is a check to see if, during install, we have the required kubernetes
  permissions to properly deploy the charm.  If we do not, we raise a `BlockedStatus` with
  a clear message.
-->

### Instructions for testing
<!--
Provide a clear, step by step instruction of how to test this feature.  Provide
screenshots, scripts, or other instructions as needed.  Even though you have
unit and integration tests (you have tests, right?), explain here how a human can test
your code.

Example:
  To test normal operation:
  1. `juju deploy myCharm --trust`
  2. (wait for deployment to occur - the charm should progress to `Active`)

  To test the error catch added in this PR:
  1. `juju deploy myCharm` (omitting `--trust`)
  2. (wait for deployment to occur - the charm should progress to 
     `BlockedStatus("Charm missing required permissions - did you deploy with --trust?"))
-->

### Referenced issues
<!--
Reference any issues this might be related to (these could also be mentioned in the 
descriptions above).  If this PR will fully address an open issue, use a 
[github keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)
to ensure when this PR closes, the issue is closed. 

Example:
  This PR closes #XXXX  <--invokes a github keyword that will close XXXX when this PR closes
  #YYYY was considered here <-- just a comment for readers, but does not close YYYY like above
-->

### PR checklist
<!--
Before opening for review, ensure the below items have been completed

If you open this PR first as a draft, it is not expected that you have completed all items until you
remove draft status
-->

* [ ] PR includes unit tests on all new code
* [ ] MOAR ITEMS COMING!!!
