name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before submitting your issue, please make
        sure you are using the latest version of the charm. If not, please switch to the latest version 
        prior to posting your report to make sure it's not already solved.

        Some fields below have a starting structure, but feel free to add/remove headings as suits the
        issue
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: >
        Provide a clear description of what you did, observed, and expected.  If 
        applicable, add screenshots to help explain your problem.  You can reference debug logs here,
        but focus more on the narative and put large raw logs down in the separate box below.
      value: |
        #### What did I do

        #### What did I observe

        #### What did I expect
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: >
        Please provide a specific, step-by-step instruction of how to reproduce the behavior.
      placeholder: |
        1. `juju deploy ...`
        2. `juju relate ...`
        3. `juju status --relations`
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >
        Please provide the context in which you run the charm.
        - Are you running Juju locally, on lxd, in multipass or on some other platform?
        - What track and channel you deployed the charm from (ie. `latest/edge` or similar).
        - Version of any applicable components, like the juju snap, the model controller, lxd, microk8s, and/or multipass.
        Output from `juju status` may also be appropriate here
      value: |
        #### How are you running juju?

        #### What track/channel have you deployed your charm from?

        #### Versions of other applicable components:

    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        Fetch the logs using `juju debug-log --replay` and `kubectl logs ...`. Additional details available in the juju docs 
        at https://juju.is/docs/olm/juju-logs
      render: shell
      value: |
        #### `juju debug-log --replay [-i mycharm]`

        #### `kubectl logs ____`

        #### ...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else that might help is solve this problem?
